name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Debug secrets
      run: |
        echo "Username length: ${#DOCKER_USERNAME}"
        echo "Password length: ${#DOCKER_PASSWORD}"
        echo "Username first char: ${DOCKER_USERNAME:0:1}"
        echo "Username last char: ${DOCKER_USERNAME: -1}"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ros2-self-driving-car:latest
        platforms: linux/amd64
